---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  prefix: /
  service: {{ include "app.fullname" . }}.demo
  # add weight condition
  {{ if gt .Values.canary.weight "0" }}weight: {{ .Values.canary.weight }} {{ end }}
  
	