---
apiVersion: v1
kind: Pod
metadata:
  name: app-secret
spec:
  containers:
  - name: mypod
    image: redis
    resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: secret1
