---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-d
  labels:
    id: hw2
    app: demo-d
  namespace: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-d
  template:
    metadata:
      labels:
        app: demo-d
        id: hw2
    spec:
      containers:
      - name: demo-d
        image: andriibondar/single-line-server:v5.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
