---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ascii
  namespace: {{ .Release.Namespace }}
  labels:
    version: {{ .Values.app.version }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ascii
  replicas: {{ .Values.ascii.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ascii
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: ascii
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        command:
          - ./app
          - "-role"
          - "ascii"
          - "-server"
          - {{ .Values.nats.service.name }}
        imagePullPolicy: Always
        env:
          - name: APP_DATASTORE
            value: "{{ .Values.data.svc }}"
          - name: APP_DB
            value: "root@tcp(db:3306)/demo"
          - name: APP_CACHE
            value: "{{ .Values.cache.svc }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: http
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.ascii.port }}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: {{ .Values.ascii.port }}
          periodSeconds: 3

