{{ if .Values.ns.enable }}
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: {{ .Release.Namespace | default "demo" }}
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
{{- end}}