group_1:
  hosts:
    host_1:
      ansible_host: 18.193.106.75

group_2:
  hosts:
    host_2:
      ansible_host: 18.197.142.237

group_3:
  hosts:
    host_3:
      ansible_host: 18.184.222.194

group_4:
  hosts:
    host_4:
      ansible_host: 52.29.116.232

iaas:
  children:
    group_1:
    group_2:

debian:
  children:
    group_1:
    group_3:
  vars:
    ansible_user: ubuntu

amazon:
  children:
    group_2:
    group_4:
  vars:
    ansible_user: ec2-user

all:
  vars:
    ansible_ssh_private_key_file: "/home/green/.aws/basecamp.pem"
