group_0:
  hosts:
    host_0:
      ansible_host: 18.185.71.189
group_1:
  hosts:
    host_1:
      ansible_host: 54.93.126.184
group_2:
  hosts:
    host_2:
      ansible_host: 18.156.171.196
group_3:
  hosts:
    host_3:
      ansible_host: 54.93.115.45

iaas:
  children:
    group_0:
    group_1:

all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/home/green/.aws/basecamp.pem"
