group_0:
  hosts:
    host_0:
      ansible_host: 18.196.14.51
group_1:
  hosts:
    host_1:
      ansible_host: 3.125.116.24
group_2:
  hosts:
    host_2:
      ansible_host: 52.59.202.176
group_3:
  hosts:
    host_3:
      ansible_host: 18.194.42.201

iaas:
  children:
    group_0:
    group_1:

all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/home/green/.aws/basecamp.pem"
