---
# Number of characters in the new password that must not be present in the
# old password.
pwquality_difok: 1

# Minimum acceptable size for the new password (plus one if
# credits are not disabled which is the default). (See pam_cracklib manual.)
# Cannot be set to lower value than 6.
pwquality_minlen: 8

# The maximum credit for having digits in the new password. If less than 0
# it is the minimum number of digits in the new password.
pwquality_dcredit: 0

# The maximum credit for having uppercase characters in the new password.
# If less than 0 it is the minimum number of uppercase characters in the new
# password.
pwquality_ucredit: 0

# The maximum credit for having lowercase characters in the new password.
# If less than 0 it is the minimum number of lowercase characters in the new
# password.
pwquality_lcredit: 0

# The maximum credit for having other characters in the new password.
# If less than 0 it is the minimum number of other characters in the new
# password.
pwquality_ocredit: 0

# The minimum number of required classes of characters for the new
# password (digits, uppercase, lowercase, others).
pwquality_minclass: 0

# The maximum number of allowed consecutive same characters in the new password.
# The check is disabled if the value is 0.
pwquality_maxrepeat: 0

# The maximum number of allowed consecutive characters of the same class in the
# new password.
# The check is disabled if the value is 0.
pwquality_maxclassrepeat: 0

# Whether to check for the words from the passwd entry GECOS string of the user.
# The check is enabled if the value is not 0.
pwquality_gecoscheck: 0

# Whether to check for the words from the cracklib dictionary.
# The check is enabled if the value is not 0.
pwquality_dictcheck: 1
#
# Whether to check if it contains the user name in some form.
# The check is enabled if the value is not 0.
pwquality_usercheck: 1
#
# Whether the check is enforced by the PAM module and possibly other
# applications.
# The new password is rejected if it fails the check and the value is not 0.
pwquality_enforcing: 1
#
# Path to the cracklib dictionaries. Default is to use the cracklib default.
pwquality_dictpath:
#
# Prompt user at most N times before returning with error. The default is 1.
pwquality_retry: 3
#
# Enforces pwquality checks on the root user password.
# Enabled if the option is present.
pwquality_enforce_for_root: enforce_for_root
#
# Skip testing the password quality for users that are not present in the
# /etc/passwd file.
# Enabled if the option is present.
# local_users_only
